<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/public/bootstrap.min.css">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Országok</a>

    <?php if($params['isAuthorized']): ?>
        <form action="/logout" method="POST">
            <button type="submit" class="btn btn-sm btn-danger m-2">Kijelentkezés</button>
        </form>
    <?php endif; ?>

    </nav>
    <?= $params['content'] ?>

</body>

</html>